---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS CloudFormation stack to create infra for a serverless cognito-protected photo gallery

Parameters:
  Stage:
    Type: String
    AllowedValues:
    - staging
    - production
    Default: staging
    Description: Stage that can be added to resource names

Mappings:
  StageMap:
    staging:
      websiteTitle: "tatooinelabs.zoubix.net"
      website: "tatooinelabs.zoubix.net"
      sourcebucketname: "tatooinelabs-src"
      resizedbucketname: "tatooinelabs-rs"
    production:
      websiteTitle: "tatooine.zoubix.net"
      website: "tatooine.zoubix.net"
      sourcebucketname: "tatooine-src"
      resizedbucketname: "tatooine-rs"

Resources:
  #
  # Source bucket creation (the one where original pictures are uploaded)
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap [StageMap, !Ref Stage, sourcebucketname]
  #
  # Resized bucket creation (the one where resized pictures are uploaded by lambda function)
  ResizedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !FindInMap [StageMap, !Ref Stage, resizedbucketname]
  #
