AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sample SAM configuration for Lambda@Edge SessionChecker (cloudFront and lambda)

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - staging
      - production
    Default: staging
    Description: Stage that can be added to resource names

Mappings:
  StageMap:
    staging:
      name: "labs"
      alias: "tatooinelabs.zoubix.net"
      originid:
      sessiontable: "test-congitoSessionManager-SessionTable-13N11D33S9561"
      sessiontableregion: "eu-west-3"
      cookiename: "Barrier"
      loginurl: "https://d1w77mu32577ph.cloudfront.net/_identity/login"
    production:
      name: "prod"
      alias: "tatooine.zoubix.net"
      originid:
      webbucketname: "tatooine-web"
      certarn:

Resources:
    # SessionChecker
  SessionCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri:
      Role: !GetAtt SessionCheckerFunctionRole.Arn
      Runtime: python3.7
      Handler: handler.handler
      Timeout: 3
      MemorySize: 128
      AutoPublishAlias: live
      Environment:
        Variables:
          SESSION_TABLE:
            Ref: sessiontable
          SESSION_TABLE_REGION:
            Ref: sessiontableregion
          COOKIE_NAME:
            Ref: cookiename
          LOGIN_URL:
            Ref: loginurl


  SessionCheckerFunctionRole:
    Type: "AWS::IAM::Role"
    Properties:
        Path: "/"
        ManagedPolicyArns:
            - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Sid: "AllowLambdaServiceToAssumeRole"
              Effect: "Allow"
              Action:
                - "sts:AssumeRole"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
                  - "edgelambda.amazonaws.com"

Outputs:
    SessionCheckerFunctionVersion:
      Description: Lambda@Edge Sample Function ARN with Version
      Value: !Ref LambdaEdgeFunctionSample.Version
